guard :rspec, cmd: 'bundle exec rspec --color --format=documentation' do 
	
	watch(%r{^spec/.+_spec\.rb$})
	watch(%r{^models/(.+)\.rb$}) {|m| "spec/#{m[1]}_spec.rb"}
	watch("blogapp.rb") {|m| "spec/blogapp_spec.rb"}
	
end